INSERT INTO categorias (nombre, descripcion, created_at, updated_at) VALUES
('Accesorios de Laboratorio', NULL, NOW(), NOW()),
('Agitadores de Laboratorio', NULL, NOW(), NOW()),
('Analizadores de alimentos', NULL, NOW(), NOW()),
('Analizadores de Gases', NULL, NOW(), NOW()),
('Analizadores de Texturas', NULL, NOW(), NOW()),
('Autoclaves de laboratorio', NULL, NOW(), NOW()),
('Balanzas de laboratorio', NULL, NOW(), NOW()),
('Baños de Laboratorio', NULL, NOW(), NOW()),
('Baños Ultrasónicos', NULL, NOW(), NOW()),
('Biorreactores', NULL, NOW(), NOW()),
('Bombas y compresores de Laboratorio', NULL, NOW(), NOW()),
('Buretas y Dispensadores', NULL, NOW(), NOW()),
('Cabinas de Ventilación de Laboratorio', NULL, NOW(), NOW()),
('Calorímetros', NULL, NOW(), NOW()),
('Cámaras Climáticas de Laboratorio', NULL, NOW(), NOW()),
('Campanas Extractoras', NULL, NOW(), NOW()),
('Centrífugas', NULL, NOW(), NOW()),
('Certificados De Calibración Acreditado', NULL, NOW(), NOW()),
('Certificados De Calibración Trazable', NULL, NOW(), NOW()),
('Congeladores de laboratorio', NULL, NOW(), NOW()),
('Consumibles de Laboratorio', NULL, NOW(), NOW()),
('Contadores de Colonias', NULL, NOW(), NOW()),
('Criostatos', NULL, NOW(), NOW()),
('Densímetros', NULL, NOW(), NOW()),
('Destiladores de Agua', NULL, NOW(), NOW()),
('Dispersores de laboratorios', NULL, NOW(), NOW()),
('Electroquímica', NULL, NOW(), NOW()),
('Equipos de seguridad', NULL, NOW(), NOW()),
('Espectrofotómetros', NULL, NOW(), NOW()),
('Espectroscopía', NULL, NOW(), NOW()),
('Espectroscopios', NULL, NOW(), NOW()),
('Esterilizadores de laboratorio', NULL, NOW(), NOW()),
('Estufas de Laboratorio', NULL, NOW(), NOW()),
('Evaporadores o Concentradores de Muestras', NULL, NOW(), NOW()),
('Extracción en Fase Sólida', NULL, NOW(), NOW()),
('Fotómetros', NULL, NOW(), NOW()),
('Generadores de Laboratorio', NULL, NOW(), NOW()),
('Homogenizador de laboratorio', NULL, NOW(), NOW()),
('Hornos', NULL, NOW(), NOW()),
('Incubadoras de Laboratorio', NULL, NOW(), NOW()),
('Instrumentos Analíticos', NULL, NOW(), NOW()),
('Lámparas de análisis UV', NULL, NOW(), NOW()),
('Lavadores de microplacas', NULL, NOW(), NOW()),
('Limpiadores a vapor', NULL, NOW(), NOW()),
('Liofilizadores para laboratorio', NULL, NOW(), NOW()),
('Máquina de limpieza de relojes', NULL, NOW(), NOW()),
('Maquinas Laser', NULL, NOW(), NOW()),
('Materiales de Laboratorio', NULL, NOW(), NOW()),
('Medidores de punto de fusión', NULL, NOW(), NOW()),
('Mezcladores de Laboratotio', NULL, NOW(), NOW()),
('Microscopios', NULL, NOW(), NOW()),
('Mobiliarios de laboratorio', NULL, NOW(), NOW()),
('Molinos', NULL, NOW(), NOW()),
('Molinos de Laboratorio', NULL, NOW(), NOW()),
('Pesas Patrón', NULL, NOW(), NOW()),
('Pipetas de Laboratorio', NULL, NOW(), NOW()),
('Placas de Calentamiento', NULL, NOW(), NOW()),
('Polarímetros', NULL, NOW(), NOW()),
('Reactores de Alta Viscosidad', NULL, NOW(), NOW()),
('Reactores de Síntesis', NULL, NOW(), NOW()),
('Refractómetros', NULL, NOW(), NOW()),
('Refrigeradores de Laboratorio', NULL, NOW(), NOW()),
('Reómetros', NULL, NOW(), NOW()),
('Rotavapores', NULL, NOW(), NOW()),
('Servicio de Mantenimiento Equipos de Laboratorio', NULL, NOW(), NOW()),
('Sistemas de extracción de ADN-ARN y purificación de proteínas', NULL, NOW(), NOW()),
('Sistemas de Histotecnología', NULL, NOW(), NOW()),
('Sistemas de Limpieza UV', NULL, NOW(), NOW()),
('Software de Laboratorio', NULL, NOW(), NOW()),
('Tamizadora', NULL, NOW(), NOW()),
('Tamizadores', NULL, NOW(), NOW()),
('Termobloques', NULL, NOW(), NOW()),
('Termostatos de Laboratorio', NULL, NOW(), NOW()),
('Trituradores de Laboratorio', NULL, NOW(), NOW()),
('Viscosímetros', NULL, NOW(), NOW());
