INSERT INTO subcategorias (nombre, id_categoria) VALUES
('Accesorios de Laboratorio', 1),
('Accesorios de Agitadores', 1),
('Accesorios de Agitadores de Hélice', 1),
('Accesorios de Agitadores de Incubación', 1),
('Accesorios de Agitadores de Laboratorio', 1),
('Accesorios de Agitadores de Microplacas', 1),
('Accesorios de Agitadores de Rodillo', 1),
('Accesorios de Agitadores de vórtex', 1),
('Accesorios de Agitadores Magnéticos', 1),
('Accesorios de Agitadores Orbitales', 1),
('Accesorios de Agitadores Oscilantes', 1),
('Accesorios de Agitadores Rotativos', 1),
('Accesorios de Agitadores Térmicos', 1),
('Accesorios de Analizador de texturas', 1),
('Accesorios de Analizadores de alimentos', 1),
('Accesorios de Autoclaves', 1),
('Accesorios de Balanzas', 1),
('Accesorios de Baño Ultrasónico', 1),
('Accesorios de Baños de Laboratorio', 1),
('Accesorios de Baños Maria', 1),
('Accesorios de Biorreactores', 1),
('Accesorios de Bombas y compresores', 1),
('Accesorios de Buretas y dispensadores', 1),
('Accesorios de Cabinas de Flujo Laminar', 1),
('Accesorios de Cabinas de Ventilación de Laboratorio', 1),
('Accesorios de Calorímetros', 1),
('Accesorios de Cámaras Climáticas', 1),
('Accesorios de Cámaras Climáticas de Laboratorio', 1),
('Accesorios de Campanas Extractoras', 1),
('Accesorios de Centrífugas', 1),
('Accesorios de Congeladores', 1),
('Accesorios de Congeladores de laboratorio', 1),
('Accesorios de Contadores de Colonias', 1),
('Accesorios de Densímetros', 1),
('Accesorios de Desecadores', 1),
('Accesorios de Destiladores y Purificadores de Agua', 1),
('Accesorios de Dispersores', 1),
('Accesorios de Esterilizadores', 1),
('Accesorios de Esterilizadores de laboratorio', 1),
('Accesorios de Estufas', 1),
('Accesorios de Fotómetros', 1),
('Accesorios de Generadores de Laboratorio', 1),
('Accesorios de Homogeneizadores', 1),
('Accesorios de Hornos', 1),
('Accesorios de Incubadoras', 1),
('Accesorios de Incubadoras de Laboratorio', 1),
('Accesorios de Instrumentos Analíticos', 1),
('Accesorios de Kit de electroquímica', 1),
('Accesorios de Laboratorio', 1),
('Accesorios de Lavadores de microplacas', 1),
('Accesorios de Limpiadores a vapor', 1),
('Accesorios de Microscopios', 1),
('Accesorios de Mobiliarios de laboratorio', 1),
('Accesorios de Molinos', 1),
('Accesorios de Pesas Patrón', 1),
('Accesorios de Pipetas', 1),
('Accesorios de Placas de Calentamiento', 1),
('Accesorios de Polarímetros', 1),
('Accesorios de Polarímetros Automáticos', 1),
('Accesorios de probetas', 1),
('Accesorios de Reactores de alta viscosidad', 1),
('Accesorios de Reactores de síntesis', 1),
('Accesorios de Refractómetros', 1),
('Accesorios de Refrigeradores', 1),
('Accesorios de Refrigeradores de Laboratorio', 1),
('Accesorios de Reómetros', 1),
('Accesorios de Rotavapores', 1),
('Accesorios de Sistema de detección', 1),
('Accesorios de Sistemas de Limpieza UV', 1),
('Accesorios de Sistemas de purificación de agua', 1),
('Accesorios de Software de Laboratorio', 1),
('Accesorios de Tamizadoras', 1),
('Accesorios de Termobloques', 1),
('Accesorios de Termostatos', 1),
('Accesorios de Viscosímetros', 1),
('Accesorios Sistemas de extracción de ADN-ARN y purificación de proteínas', 1),
('Liofilizadores con trampa de enfriamiento', 1),
('Agitadores de Laboratorio', 2),
('Agitadores de Hélice', 2),
('Agitadores de Incubación', 2),
('Agitadores de Laboratorio', 2),
('Agitadores de Microplacas', 2),
('Agitadores de Rodillos', 2),
('Agitadores de Varillas', 2),
('Agitadores Magnéticos', 2),
('Agitadores Orbitales', 2),
('Agitadores Oscilantes', 2),
('Agitadores Recíprocos', 2),
('Agitadores Rotativos', 2),
('Agitadores Térmicos', 2),
('Agitadores Vortex', 2),
('Analizadores de alimentos', 3),
('Determinadores de Fibra', 3),
('Determinadores de Fósforo', 3),
('Determinadores de Grasa', 3),
('Determinadores de Proteínas', 3),
('Digestores de Laboratorio', 3),
('Analizadores de Gases', 4),
('Analizadores de gases para concentraciones de O 2 y CO 2', 4),
('Analizadores de gases para medición de O 2 y CO 2', 4),
('Analizadores de Texturas', 5),
('Autoclaves de laboratorio', 6),
('Autoclaves de Mesa', 6),
('Autoclaves Horizontales', 6),
('Autoclaves Vertical', 6),
('Esterilizadores a Vapor Sin Presión', 6),
('Balanzas de laboratorio', 7),
('Balanzas Analíticas', 7),
('Balanzas Antiexplosión', 7),
('Balanzas Colgantes', 7),
('Balanzas Contadoras', 7),
('Balanzas de Bolsillo', 7),
('Balanzas de Densidad', 7),
('Balanzas de Humedad', 7),
('Balanzas de Joyeria', 7),
('Balanzas de laboratorio', 7),
('Balanzas de Mesa', 7),
('Balanzas de Piso', 7),
('Balanzas de Precisión', 7),
('Balanzas de Quilates', 7),
('Balanzas Escolares', 7),
('Balanzas Mecánicas', 7),
('Balanzas para bebés y niños pequeños', 7),
('Balanzas para Paqueteria', 7),
('Balanzas Semi-Micro', 7),
('Balanzas Triple Brazo', 7),
('Báscula Contadora', 7),
('Básculas de Transpaletas', 7),
('Microbalanzas', 7),
('Baños de Laboratorio', 8),
('Baños de Aceite para Laboratorio', 8),
('Baños de Ebullición', 8),
('Baños de Flotación', 8),
('Baños de Laboratorio', 8),
('Baños María Con Agitación', 8),
('Baños Maria Con Agitador Magnético', 8),
('Baños María Refrigerada', 8),
('Baños Maria Sin Agitación', 8),
('Baños María Sin Agitación', 8),
('Baños Ultrasónicos', 9),
('Baños Ultrasónicos Análogos', 9),
('Baños Ultrasónicos Digitales', 9),
('Baños Ultrasónicos Industriales', 9),
('Baños Ultrasónicos Profesionales', 9),
('Biorreactores', 10),
('Biorreactores personales', 10),
('Fotobiorreactores', 10),
('Paquetes de Modelo Control', 10),
('Paquetes de Recipientes', 10),
('Sistema de Flujo', 10),
('Bombas y compresores de Laboratorio', 11),
('Bombas de Vacío', 11),
('Bombas de Vacío con Transmisión por Correa', 11),
('Bombas de Vacío de Diafragma', 11),
('Bombas de Vacío de Paletas Rotativas', 11),
('Bombas de Vacío seca', 11),
('Bombas de Vacío Sin Aceite', 11),
('Bombas Peristáltica', 11),
('Controlador de Vacío', 11),
('Buretas y Dispensadores', 12),
('Buretas Digitales', 12),
('Dispensadores de Laboratorio', 12),
('Cabinas de Ventilación de Laboratorio', 13),
('Cabinas de Flujo Horizontal', 13),
('Cabinas de Flujo Laminar', 13),
('Cabinas de Flujo Laminar UV de ADN/ARN', 13),
('Cabinas de Flujo Vertical', 13),
('Cabinas de Seguridad Biológica', 13),
('Calorímetros', 14),
('Calorímetros automáticos', 14),
('Calorímetros de Chaqueta Estática', 14),
('Sistemas de Descomposición', 14),
('Cámaras Climáticas de Laboratorio', 15),
('Cámaras Climáticas', 15),
('Cámaras Climáticas Visitables', 15),
('Cámaras De Calentamiento', 15),
('Cámaras de Choque Térmico', 15),
('Cámaras de Estabilidad', 15),
('Cámaras de Pruebas Ambientales', 15),
('Estantes de Crecimiento de Plantas', 15),
('Campanas Extractoras', 16),
('Depurador de Gases', 16),
('Centrífugas', 17),
('Centrífuga clínicas de baja velocidad', 17),
('Centrífugas', 17),
('Centrífugas Automatizadas', 17),
('Centrífugas de alta velocidad y gran capacidad', 17),
('Centrífugas de Mesa', 17),
('Centrífugas Multipropósito', 17),
('Centrífugas Pequeñas', 17),
('Microcentrífugas', 17),
('Certificados De Calibración Acreditado', 18),
('Calibración acreditada de balanza analítica', 18),
('Calibración Acreditado de Agitadores de Hélice', 18),
('Calibración Acreditado de Agitadores de Incubación', 18),
('Calibración Acreditado de Agitadores de Microplacas', 18),
('Calibración Acreditado de Agitadores de Rodillos', 18),
('Calibración Acreditado de Agitadores Magnéticos', 18),
('Calibración Acreditado de Agitadores Oscilantes', 18),
('Calibración Acreditado de Agitadores Recíprocos', 18),
('Calibración Acreditado de Baños de Ebullición', 18),
('Calibración Acreditado de Baños María', 18),
('Calibración Acreditado de Cámaras Climáticas', 18),
('Certificados De Calibración Trazable', 19),
('Calibración Trazable de Agitadores de Hélice', 19),
('Calibración Trazable de Agitadores de Incubación', 19),
('Calibración Trazable de Agitadores de Microplacas', 19),
('Calibración Trazable de Agitadores de Rodillos', 19),
('Calibración Trazable de Agitadores Magnéticos', 19),
('Calibración Trazable de Agitadores Orbitales', 19),
('Calibración Trazable de Agitadores Oscilantes', 19),
('Calibración Trazable de Agitadores Rotativos', 19),
('Calibración Trazable de Agitadores Térmicos', 19),
('Calibración Trazable de Agitadores Vortex', 19),
('Calibración Trazable de Analizador de Texturas', 19),
('Calibración Trazable de Autoclaves', 19),
('Calibración Trazable de Baños de Ebullición', 19),
('Calibración Trazable de Baños María', 19),
('Calibración Trazable de Baños Ultrasónicos', 19),
('Calibración Trazable de Cabinas de Flujo Laminar', 19),
('Calibración Trazable de Calorímetros', 19),
('Calibración Trazable de Centrífugas', 19),
('Calibración Trazable de Congeladores', 19),
('Calibración Trazable de Densímetros', 19),
('Calibración Trazable de Dispersores', 19),
('Calibración Trazable de Espectroscopios', 19),
('Calibración Trazable de Estufas', 19),
('Calibración Trazable de Fotómetros', 19),
('Calibración Trazable de Incubadoras', 19),
('Calibración Trazable de Microscopios', 19),
('Calibración Trazable de Pipetas', 19),
('Calibración Trazable de Placas de Calentamiento', 19),
('Calibración Trazable de Refractómetros', 19),
('Calibración Trazable de Refrigeradores', 19),
('Calibración Trazable de Reómetros', 19),
('Calibración Trazable de Rotavapores', 19),
('Calibración Trazable de Termobloques', 19),
('Calibración Trazable de Viscosímetros', 19),
('Certificado de Calibración Trazable de Balanza Analítica', 19),
('Congeladores de laboratorio', 20),
('Congeladoras de laboratorio de convección forzada', 20),
('Congeladoras de laboratorio de convección natural', 20),
('Ultra Congeladores de Laboratorio', 20),
('Consumibles de Laboratorio', 21),
('Consumibles de analizadores de alimentos', 21),
('Consumibles de Balanzas', 21),
('Consumibles de Baño Ultrasónico', 21),
('Consumibles de Baños Maria', 21),
('Consumibles de Cabinas de Flujo Laminar', 21),
('Consumibles de Cabinas de Ventilación de Laboratorio', 21),
('Consumibles de Calorímetros', 21),
('Consumibles de Cámaras Climáticas de Laboratorio', 21),
('Consumibles de Campanas Extractoras', 21),
('Consumibles de Centrífugas', 21),
('Consumibles de Congeladores de laboratorio', 21),
('Consumibles de Destiladores de Agua', 21),
('Consumibles de Esterilizadores', 21),
('Consumibles de Esterilizadores de laboratorio', 21),
('Consumibles de Fotómetro de llama', 21),
('Consumibles de Incubadoras de Laboratorio', 21),
('Consumibles de Instrumentos Analíticos', 21),
('Consumibles de Laboratorio', 21),
('Consumibles de Medidores de punto de fusión', 21),
('Consumibles de Pipetas', 21),
('Consumibles de Refractómetros', 21),
('Consumibles de Refrigeradores de Laboratorio', 21),
('Consumibles de Sistemas de extracción de ADN-ARN y purificación de proteínas', 21),
('Consumibles de Termostatos', 21),
('Consumibles de Viscosímetros', 21),
('Contadores de Colonias', 22),
('Contadores de Colonias Automático', 22),
('Contadores de Colonias Manual', 22),
('Criostatos', 23),
('Criostatos con Agitador Magnético', 23),
('Densímetros', 24),
('Densímetros automático', 24),
('Densímetros manual', 24),
('Densímetros semiautomática', 24),
('Destiladores de Agua', 25),
('Destiladores automático de agua', 25),
('Destiladores de Amoníaco', 25),
('Sistemas de purificación de agua', 25),
('Dispersores de laboratorios', 26),
('Dispersores a Escala de Laboratorio', 26),
('Dispersores de Escala Piloto', 26),
('Dispersores en Linea', 26),
('Sistemas Desechables', 26),
('Electroquímica', 27),
('Kit de electroquímica', 27),
('Sistema de detección', 27),
('Equipos de seguridad', 28),
('Cabina de Guantes', 28),
('Espectrofotómetros', 29),
('Espectrofotómetro', 29),
('Espectroscopía', 30),
('Espectrómetros de Fluorescencia', 30),
('Espectrómetros XRF de mano', 30),
('Espectroscopios', 31),
('Espectroscopio de Kirchhoff-Bunsen', 31),
('Espectroscopios portátil con Escala', 31),
('Espectroscopios portátil sin Escala', 31),
('Goniómetros y Espectrómetros', 31),
('Esterilizadores de laboratorio', 32),
('Esterilizadores de Convección Forzada', 32),
('Esterilizadores de Convección Natural', 32),
('Esterilizadores por Infrarrojo', 32),
('Esterilizadores por Llama', 32),
('Mecheros Bunsen', 32),
('Estufas de Laboratorio', 33),
('Estufas de Convección Forzada', 33),
('Estufas de Convección Natural', 33),
('Estufas de Secado', 33),
('Estufas de Vacío', 33),
('Horno de Secado de Alta Temperatura', 33),
('Horno de Secado de Limpieza', 33),
('Hornos de secado', 33),
('Evaporadores o Concentradores de Muestras', 34),
('Concentradores de Nitrógeno', 34),
('Extracción en Fase Sólida', 35),
('Sistema automático', 35),
('Fotómetros', 36),
('Fotómetros de llama automática', 36),
('Fotómetros de llama básico', 36),
('Fotómetros de microplacas', 36),
('Fotómetros Portátiles', 36),
('Generadores de Laboratorio', 37),
('Generadores de Ozono', 37),
('Generadores Eléctricos', 37),
('Homogenizador de laboratorio', 38),
('Hornos', 39),
('Hornos de convección forzada', 39),
('Hornos de Convección Natural', 39),
('Hornos de Fusión por Inducción', 39),
('Hornos de Mufla', 39),
('Incubadoras de Laboratorio', 40),
('Cultivos Anaeróbico', 40),
('Incubadora de Plaquetas', 40),
('Incubadoras con Agitación', 40),
('Incubadoras de Co2', 40),
('Incubadoras de Convección Aire Forzado', 40),
('Incubadoras de Convección Natural', 40),
('Incubadoras de Laboratorio', 40),
('Incubadoras Económicas', 40),
('Incubadoras Para Cultivos', 40),
('Incubadoras Refrigeradas', 40),
('Instrumentos Analíticos', 41),
('Electroanalizadores', 41),
('Medidor de pH', 41),
('Medidores de Aceite', 41),
('Medidores de Calcio', 41),
('Medidores de Conductividad', 41),
('Medidores de Fluoruro', 41),
('Medidores de Nitrato', 41),
('Medidores de ORP', 41),
('Medidores de Oxígeno Disuelto', 41),
('Medidores de Potasio', 41),
('Medidores de Salinidad', 41),
('Medidores de Sodio', 41),
('Medidores Multiparamétricos', 41),
('Sistemas de Ensayo de Desintegración', 41),
('Sondas y Sensores', 41),
('Unidades de Control', 41),
('Lámparas de análisis UV', 42),
('Lavadores de microplacas', 43),
('Limpiadores a vapor', 44),
('Limpiadores a vapor Básico', 44),
('Limpiadores a vapor Industrial', 44),
('Liofilizadores para laboratorio', 45),
('Cámara de Secado para Liofilizador', 45),
('Liofilizadores con trampa de enfriamiento', 45),
('Liofilizadores de Mesa', 45),
('Liofilizadores para laboratorio', 45),
('Liofilizadores Piloto', 45),
('Liofilizadores sin CFC', 45),
('Secadoras de Hielo', 45),
('Máquina de limpieza de relojes', 46),
('Máquina de limpieza Automático de relojes', 46),
('Máquina de limpieza Manual de relojes', 46),
('Maquinas Laser', 47),
('Máquinas de Marcado Láser UV', 47),
('Maquinas Láser de Diodo', 47),
('Maquinas Laser de Fibra', 47),
('Materiales de Laboratorio', 48),
('Buretas Automáticas', 48),
('Condensadores', 48),
('Crisoles', 48),
('Desecadores', 48),
('Embudos', 48),
('Frascos de Bureta', 48),
('Frascos de Laboratorio', 48),
('Frascos de lavado', 48),
('Jarras Medidoras de Laboratorio', 48),
('Llaves de paso', 48),
('Matraces Aforados', 48),
('Matraces de Erlenmeyer', 48),
('Matraces Esférico de Fondo Plano', 48),
('Matraces Esféricos', 48),
('Matraces Kjeldahl', 48),
('Microburetas', 48),
('Pipetas Automática Kipp', 48),
('Pipetas Pasteur', 48),
('Pipetas Volumétricas', 48),
('Probetas', 48),
('Sistemas de extracción', 48),
('Tapones', 48),
('Tubos de Centrífuga', 48),
('Tubos De Ensayo', 48),
('Vasos Precipitados', 48),
('Medidores de punto de fusión', 49),
('Medidores de punto de fusión automáticos', 49),
('Medidores de punto de fusión semiautomáticos', 49),
('Mezcladores de Laboratotio', 50),
('Mezcladores Digitales', 50),
('Microscopios', 51),
('Microscopios Binoculares', 51),
('Microscopios de vídeo', 51),
('Microscopios Digitales', 51),
('Microscopios Estereoscópicos', 51),
('Microscopios Invertidos', 51),
('Microscopios metalúrgicos', 51),
('Microscopios Monocular', 51),
('Microscopios Trinocular', 51),
('Mobiliarios de laboratorio', 52),
('Cajoneras de laboratorio', 52),
('Escritorios de laboratorio', 52),
('Estación de Lavado', 52),
('Gabinetes de Seguridad', 52),
('Molinos', 53),
('Cámaras de Molienda', 53),
('Molino en Linea', 53),
('Molinos de Lotes', 53),
('Sistema Desechables', 53),
('Molinos de Laboratorio', 54),
('Molinos de Bolas', 54),
('Molinos de Discos', 54),
('Molinos de Martillos', 54),
('Molinos Tipo Wiley', 54),
('Pesas Patrón', 55),
('Pesas Patrón de Clase ASTM', 55),
('Pesas Patrón de Clase OIML E', 55),
('Pesas Patrón de Clase OIML F', 55),
('Pesas Patrón de Clase OIML M', 55),
('Pipetas de Laboratorio', 56),
('Aspiradores de Pipetas', 56),
('Cargadores de Pipetas', 56),
('Pipetas Monocanal - Volumen Fijo', 56),
('Pipetas Monocanal - Volumen Variable', 56),
('Pipetas Multicanal - Volumen Variable', 56),
('Placas de Calentamiento', 57),
('Controladores de temperatura', 57),
('Placas Calefactoras', 57),
('Polarímetros', 58),
('Polarímetros Automático', 58),
('Polarímetros Automáticos', 58),
('Polarímetros Económico', 58),
('Polarímetros Manuales', 58),
('Polarímetros profesional', 58),
('Reactores de Alta Viscosidad', 59),
('Reactores de Laboratorio', 59),
('Reactores de Laboratorio Compactos', 59),
('Reactores de Síntesis', 60),
('Sistemas Advanced', 60),
('Sistemas Starter', 60),
('Refractómetros', 61),
('Refractómetro de mano', 61),
('Refractómetros Abbe', 61),
('Refractómetros de proceso', 61),
('Refractómetros digital de mano', 61),
('Refractómetros Digitales', 61),
('Refrigeradores de Laboratorio', 62),
('Congeladoras de laboratorio de convección forzada', 62),
('Congeladoras de laboratorio de convección natural', 62),
('Maquinas de Hielo', 62),
('Refrigerador Portátil', 62),
('Refrigeradores de Bancos de Sangre', 62),
('Refrigeradores de Laboratorio', 62),
('Refrigeradores Medicos', 62),
('Reómetros', 63),
('Reómetros Rotacional', 63),
('Rotavapores', 64),
('Evaporador Rotativo de Elevación Automático', 64),
('Evaporador Rotativo de Elevación Manual', 64),
('Sistema Automático con Bomba de Vacío', 64),
('Sistema Completo', 64),
('Sistemas de Aspiración', 64),
('Servicio de Mantenimiento Equipos de Laboratorio', 65),
('Mantenimiento Preventivo y/o Reparación de Baños de Ebullición', 65),
('Mantenimiento Preventivo y/o Reparación de Baños María', 65),
('Servicio de mantenimiento preventivo y/o correctivo de balanza analítica', 65),
('Electroforesis en Gel', 66),
('Fundición de Gel', 66),
('Sistemas de extracción de ADN-ARN y purificación de proteínas', 67),
('Sistemas de PCR', 67),
('Sistemas de Histotecnología', 68),
('Micrótomos', 68),
('Sistemas de Limpieza UV', 69),
('Software de Laboratorio', 70),
('Software de Balanzas', 70),
('Software de Baños Termostáticos de Circulación', 70),
('Software de calibración de pipetas', 70),
('Software de Cámaras Climáticas', 70),
('Software de Control y Evaluación para Calorímetros', 70),
('Software de Incubadoras', 70),
('Software de Medición, Control y Regulación', 70),
('Software de Viscosímetro', 70),
('Tamizadora', 71),
('Tamizadores', 72),
('Termobloques', 73),
('Calentadores de Bloque Seco', 73),
('Calentamiento y Refrigeración de Bloques seco', 73),
('Termostatos de Laboratorio', 74),
('Baños de Calibración', 74),
('Baños de viscosidad', 74),
('Baños termostáticos con Agitación Magnética', 74),
('Baños Termostáticos con Agitación Orbital', 74),
('Baños Termostáticos con Agitación Vaivén', 74),
('Baños Termostáticos de Circulación', 74),
('Baños Termostáticos De Circulación Con Refrigeración', 74),
('Baños Termostáticos para Cata de Aceite', 74),
('Enfriadores de inmersión', 74),
('Recirculadores de Laboratorio', 74),
('Termostatos de Circulación', 74),
('Trituradores de Laboratorio', 75),
('Trituradoras', 75),
('Viscosímetros', 76),
('Instrumentos medidores de torque', 76),
('Viscosímetros', 76),
('Viscosímetros Industriales', 76),
('Viscosímetros Portátiles', 76),
('Viscosímetros Rotacional', 76);
