export const countryOptions = [
    { value: "Alemania", label: "Alemania" },
    { value: "Argentina", label: "Argentina" },
    { value: "Australia", label: "Australia" },
    { value: "Brasil", label: "Brasil" },
    { value: "Canadá", label: "Canadá" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Colombia", label: "Colombia" },
    { value: "Corea del Sur", label: "Corea del Sur" },
    { value: "Dinamarca", label: "Dinamarca" },
    { value: "Egipto", label: "Egipto" },
    { value: "Emiratos Árabes Unidos", label: "Emiratos Árabes Unidos" },
    { value: "España", label: "España" },
    { value: "Estados Unidos", label: "Estados Unidos" },
    { value: "Francia", label: "Francia" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Italia", label: "Italia" },
    { value: "Japón", label: "Japón" },
    { value: "México", label: "México" },
    { value: "Noruega", label: "Noruega" },
    { value: "Nueva Zelanda", label: "Nueva Zelanda" },
    { value: "Países Bajos", label: "Países Bajos" },
    { value: "Perú", label: "Perú" },
    { value: "Polonia", label: "Polonia" },
    { value: "Portugal", label: "Portugal" },
    { value: "Reino Unido", label: "Reino Unido" },
    { value: "Rusia", label: "Rusia" },
    { value: "Singapur", label: "Singapur" },
    { value: "Sudáfrica", label: "Sudáfrica" },
    { value: "Suecia", label: "Suecia" },
    { value: "Suiza", label: "Suiza" },
    { value: "Tailandia", label: "Tailandia" },
    { value: "Turquía", label: "Turquía" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" }
];
